[audio]
enable_sounds = true

[backdrop]
enabled = true

[bar.default]
background_opacity = 0.0
capsule = true
capsule_border = "primary"
capsule_opacity = 0.65
capsule_padding = 10.0
capsule_radius = 8
capsule_thickness = 0.75
center = []
concave_edge_corners = false
end = [
    "group:g1",
    "spacer_2",
    "network",
    "battery",
    "volume",
    "input_volume",
    "tray",
    "spacer_1",
    "control-center",
    "notifications"
]
font_family = "Inter 18pt"
font_weight = 600
icon_color = "primary"
margin_ends = 0
padding = 5
radius = 0
start = [ "clock", "workspaces", "media" ]
widget_spacing = 5

    [bar.default.dead_zone.actions]
    right = "none"

    [[bar.default.capsule_group]]
    border = "primary"
    enabled = true
    fill = "surface_variant"
    id = "g1"
    members = [ "temp", "sysmon", "ram" ]
    opacity = 0.65
    padding = 10.0
    radius = 8.0

[desktop_widgets]
schema_version = 2
widget_order = [ "desktop-widget-0000000000000001", "desktop-widget-0000000000000002", "desktop-widget-0000000000000003" ]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    box_height = 128.0
    box_width = 416.0
    cx = 960.0
    cy = 236.0
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "clock"

        [desktop_widgets.widget.desktop-widget-0000000000000001.settings]
        background = false
        center_text = true
        clock_style = "digital"
        color = "on_surface"
        font_family = "JetBrainsMono NFP ExtraBold"

    [desktop_widgets.widget.desktop-widget-0000000000000002]
    box_height = 0.0
    box_width = 0.0
    cx = 960.0
    cy = 860.0
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "fancy_audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000002.settings]
        background = false
        inner_diameter = 0.5
        secondary_color = "secondary"
        sensitivity = 1.0

    [desktop_widgets.widget.desktop-widget-0000000000000003]
    box_height = 80.0
    box_width = 336.0
    cx = 960.0
    cy = 320.8
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "weather"

        [desktop_widgets.widget.desktop-widget-0000000000000003.settings]
        background = false
        color = "on_surface"
        font_family = "JetBrainsMono NFP ExtraBold"
        shadow = true
        show_forecast = false

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 1800.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 2700.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 3600.0

[location]
auto_locate = true

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "lockscreen-login-box@WAYLAND-1",
    "lockscreen-login-box@winit",
    "lockscreen-widget-0000000000000001",
    "lockscreen-login-box",
    "lockscreen-widget-0000000000000002",
    "lockscreen-widget-0000000000000003",
    "lockscreen-widget-0000000000000004",
    "lockscreen-widget-0000000000000005",
    "lockscreen-widget-0000000000000006",
    "lockscreen-widget-0000000000000007",
    "lockscreen-widget-0000000000000008"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box"]
    box_height = 70.0
    box_width = 400.0
    cx = 960.0
    cy = 1001.0
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "compact"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@WAYLAND-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 476.0
    cy = 854.0
    output = "WAYLAND-1"
    placement_height = 0.0
    placement_width = 0.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@WAYLAND-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@winit"]
    box_height = 196.0
    box_width = 810.0
    cx = 471.0
    cy = 820.0
    output = "winit"
    placement_height = 0.0
    placement_width = 0.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@winit".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 80.0
    box_width = 400.0
    cx = 960.0
    cy = 881.0
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "audio_visualizer"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = false
        bands = 80
        centered = false
        mirrored = true
        show_when_idle = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 128.0
    box_width = 416.0
    cx = 960.0
    cy = 236.0
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        background = false
        center_text = true
        clock_style = "digital"
        color = "on_surface"
        font_family = "JetBrainsMono NFP ExtraBold"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000003]
    box_height = 80.0
    box_width = 336.0
    cx = 960.0
    cy = 320.8
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "weather"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000003.settings]
        background = false
        color = "on_surface"
        font_family = "JetBrainsMono NFP ExtraBold"
        shadow = true
        show_forecast = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000004]
    box_height = 224.0
    box_width = 144.0
    cx = 88.0
    cy = 124.0
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "media_player"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000004.settings]
        background = true
        hide_when_no_media = true
        layout = "vertical"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000005]
    box_height = 48.0
    box_width = 32.0
    cx = 960.0
    cy = 36.0
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "label"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000005.settings]
        background = false
        background_opacity = 0.0
        background_padding = 5
        background_radius = 0
        color = "primary"
        font_family = "JetBrainsMonoNL NFP ExtraBold"
        opacity = 1.0
        title = "󰌾"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000006]
    box_height = 112.0
    box_width = 176.0
    cx = 1816.0
    cy = 68.0
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "sysmon"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000006.settings]
        display = "graph"
        gauge_layout = "horizontal"
        stat = "cpu_usage"
        stat2 = "cpu_temp"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000007]
    box_height = 112.0
    box_width = 176.0
    cx = 1816.0
    cy = 187.0
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "sysmon"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000007.settings]
        stat = "gpu_usage"
        stat2 = "gpu_temp"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000008]
    box_height = 112.0
    box_width = 176.0
    cx = 1816.0
    cy = 308.0
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "sysmon"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000008.settings]
        stat = "ram_pct"
        stat2 = "swap_pct"

[notification]
layer = "overlay"

[osd]
background_opacity = 1
position = "bottom_center"
position_vertical = "top_left"

    [osd.kinds]
    media = false
    privacy = false

[shell]
app_icon_color = "primary"
font_family = "Inter 18pt Medium"
niri_overview_type_to_launch_enabled = true
password_style = "random"
polkit_agent = true
screen_time_enabled = true

    [shell.panel]
    control_center_placement = "floating"
    open_near_click_control_center = true
    session_placement = "floating"
    transparency_mode = "glass"
    wallpaper_placement = "floating"

    [[shell.session.actions]]
    action = "lock"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "command"
    command = "systemctl hibernate"
    countdown_seconds = 0.0
    enabled = true
    glyph = "hibernate"
    label = "Hibernate"
    shortcut = "4"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "5"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "6"
    variant = "destructive"

    [shell.shadow]
    direction = "down_right"

[theme]
source = "wallpaper"
wallpaper_scheme = "m3-tonal-spot"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "kcolorscheme", "niri", "qt" ]
    community_ids = [ ]

[widget.battery]
icon_color = "primary"

[widget.control-center]
color = "primary"
glyph = "adjustments"

[widget.input_volume]
icon_color = "primary"

[widget.media]
title_scroll = "on_hover"

    [widget.media.actions]
    scroll_up = "media previous"
    scroll_down = "media next"

[widget.network]
icon_color = "primary"
show_label = false

[widget.notifications]
icon_color = "primary"

[widget.ram]
icon_color = "primary"
visualization = "none"

[widget.spacer_1]
type = "spacer"

[widget.spacer_2]
type = "spacer"

[widget.sysmon]
glyph = "gpu-usage"
icon_color = "primary"
show_value = true
stat = "gpu_temp"
visualization = "none"

[widget.temp]
icon_color = "primary"
visualization = "none"

[widget.tray]
drawer = true
icon_color = "primary"

[widget.volume]
icon_color = "primary"

[widget.workspaces]
active_pill_size = 1.65
focused_output_only = true
hide_when_empty = true
style = "focus_hint"
