cursor #ffffff
cursor_text_color #ffffff

foreground            #ffffff
background            #14161a
selection_foreground  #ffffff
selection_background  #322d8b
url_color             #d18771

color0   #14161a
color1   #e06c75
color2   #3bcb8b
color3   #ebcb8b
color4   #528bff
color5   #9980ff
color6   #52cbff
color7   #c0c0c0

color8   #465173
color9   #ff5760
color10  #00ce67
color11  #ffd780
color12  #3080ff
color13  #c485ff
color14  #20c0ff
color15  #ffffff
